[package]
name = "hi"
version = "0.1.0"
authors = ["Daniel Ferguson <danielferguson@me.com>"]
edition = "2018"

[dependencies]
env_logger = "0.3"
log = "0.3.8"
termion = "1.4.0"

[dependencies.nom]
version = "3.2"
